name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        --env BUNDLE_PATH=/tmp/bundle \
        --env GEM_HOME=/tmp/gems \
        --env GEM_PATH=/tmp/gems \
        --user $(id -u):$(id -g) \
        -v ${{ github.workspace }}:/srv/jekyll:z \
        -v ${{ github.workspace }}/_site:/srv/jekyll/_site:z \
        jekyll/builder:latest /bin/bash -c "\
          mkdir -p /tmp/bundle && \
          mkdir -p /tmp/gems && \
          bundle install && \
          jekyll build --future --verbose --trace"
