name: Check SCSS

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-scss:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Run SCSS Linter
      run: |
        docker run \
          --env BUNDLE_PATH=/tmp/bundle \
          --env GEM_HOME=/tmp/gems \
          --env GEM_PATH=/tmp/gems \
          -v ${{ github.workspace }}:/srv/jekyll:z \
          -u root \
          jekyll/builder:latest /bin/bash -c "\
            gem install sass && \
            find . -name '*.scss' -exec sass --no-source-map --check {} \;"

