name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Afficher le contenu de main.scss
      run: |
        if [ -f assets/main.scss ]; then
          echo "Le fichier main.scss existe, voici son contenu :"
          cat assets/main.scss
        else
          echo "Le fichier main.scss n'existe pas."
        fi

    - name: Vérifier les permissions
      run: |
        ls -l assets/
        ls -l

    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        --user $(id -u):$(id -g) \
        -v ${{ github.workspace }}:/srv/jekyll \
        -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "\
          chmod -R 755 /srv/jekyll && \
          bundle install && \
          bundle exec jekyll build --future --verbose --trace"
