name: Jekyll Build, SCSS Check, and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true

    - name: Install dependencies
      run: bundle install
      working-directory: ${{ github.workspace }}

    - name: Check SCSS files
      run: |
        if ls assets/**/*.scss 1> /dev/null 2>&1; then
          echo "SCSS files found, checking..."
          bundle exec sass --check assets/**/*.scss
        else
          echo "No SCSS files to check"
        fi

    - name: Build Jekyll site
      run: bundle exec jekyll build --verbose
      working-directory: ${{ github.workspace }}

    - name: Upload Jekyll build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: _site
        path: _site

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git config --global --add safe.directory $GITHUB_WORKSPACE
        git config --global init.defaultBranch gh-pages
        cd _site
        git init
        git add .
        git commit -m "Deploy to GitHub Pages"
        git remote add origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
        git push --force origin gh-pages
