name: CI/CD for Jekyll Site

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  check-scss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Adjust the Ruby version if needed

      - name: Install dependencies
        run: |
          bundle config path vendor/bundle
          bundle install

      - name: Check SCSS files
        run: |
          bundle exec sass --check assets/css/*.scss

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: check-scss

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Adjust the Ruby version if needed

      - name: Install dependencies
        run: |
          bundle config path vendor/bundle
          bundle install

      - name: Build the Jekyll site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          cd _site
          git init
          git remote add origin https://github.com/${{ github.repository }}
          git checkout -b gh-pages
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }} gh-pages

      - name: Clean up
        run: |
          rm -rf _site
