name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        --user $(id -u):$(id -g) \
        -v ${{ github.workspace }}:/srv/jekyll \
        -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "\
          mkdir -p /.local/share/gem/ruby/3.1.0/cache && \
          cd /srv/jekyll && \
          gem install bundler && \
          bundle install && \
          bundle exec jekyll build --future --verbose"
