name: Check SCSS

on: [push, pull_request]

jobs:
  check-scss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker environment variables
        run: |
          docker run \
            --user $(id -u):$(id -g) \
            -v ${{ github.workspace }}:/srv/jekyll:z \
            --env GEM_HOME=/tmp/gems \
            --env GEM_PATH=/tmp/gems \
            --env BUNDLE_PATH=/tmp/bundle \
            jekyll/builder:latest /bin/bash -c "\
              mkdir -p /tmp/gems && \
              mkdir -p /tmp/bundle && \
              apt-get update && \
              apt-get install -y curl && \
              curl -L https://sass-lang.com/install.sh | bash && \
              sass --no-source-map --check /srv/jekyll/assets/main.scss"
