name: Jekyll Build, SCSS Check, and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true

    - name: Install dependencies
      run: bundle install
      working-directory: ${{ github.workspace }}

    - name: Check SCSS files
      run: |
        if ls assets/**/*.scss 1> /dev/null 2>&1; then
          echo "SCSS files found, checking..."
          bundle exec sass --check assets/**/*.scss
        else
          echo "No SCSS files to check"
        fi

    - name: Build Jekyll site
      run: bundle exec jekyll build --verbose
      working-directory: ${{ github.workspace }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _site
        # if you want to deploy to a custom domain, you can uncomment and set the cname option
        # cname: 'www.example.com'

    - name: Upload Jekyll build artifacts
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: _site
        path: _site
