name: Check SCSS

on: [push, pull_request]

jobs:
  check-scss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run SCSS Linter
        run: |
          docker run \
            --user $(id -u):$(id -g) \
            -v ${{ github.workspace }}:/srv/jekyll:z \
            jekyll/builder:latest /bin/bash -c "\
              gem install sass && \
              sass --no-source-map --check /srv/jekyll/assets/main.scss"
