name: Build Jekyll Site

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker container for Jekyll
      run: docker run \
        --env BUNDLE_PATH=/tmp/bundle \
        --env GEM_HOME=/tmp/gems \
        --env GEM_PATH=/tmp/gems \
        --user $(id -u):$(id -g) \
        -v ${{ github.workspace }}:/srv/jekyll:z \
        -v ${{ github.workspace }}/_site:/srv/jekyll/_site:z \
        jekyll/builder:latest /bin/bash -c "\
          mkdir -p /tmp/bundle && \
          mkdir -p /tmp/gems && \
          bundle install && \
          jekyll build --future --verbose --trace"

    - name: Upload _site folder as artifact
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: site
        path: _site

    - name: Deploy to GitHub Pages
      if: success() && github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _site
