name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: List assets directory
      run: ls -R assets || echo "No assets directory found"

    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        --user $(id -u):$(id -g) \
        -v ${{ github.workspace }}:/srv/jekyll \
        -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "\
          mkdir -p /srv/jekyll/.gem && \
          export GEM_HOME=/srv/jekyll/.gem && \
          export GEM_PATH=/srv/jekyll/.gem && \
          cd /srv/jekyll && \
          gem install bundler && \
          bundle install && \
          bundle exec jekyll build --future --verbose --trace"
